name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW32
          install: >-
            mingw-w64-i686-toolchain
            make

      - name: Build project
        shell: cmd
        run: |
          call C:\msys64\mingw32.exe /bin/bash -lc "make clean || true && make default_GLOBAL_INCS= default_GLOBAL_LIBDIRS="

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: chp
          path: chp.exe
