name: Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: false
          msystem: MINGW32
          install: >-
            mingw-w64-i686-toolchain
            make

      - name: Build project
        shell: msys2 {0}
        run: |
          pacman --noconfirm -Syuu || true
          make clean || true
          make

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: chp
          path: ./chp.exe
          if-no-files-found: error
